"""The full Primer curriculum: topics, their concept lists, and the projects.

This is plain data. The frontend renders the roadmap from `PHASES` and drives the
per-topic progress rail from each topic's `concepts` list. Concept lists are taken
directly from the Primer specification so the rail matches what Primer teaches.
"""
from __future__ import annotations

from typing import Optional

# ---------------------------------------------------------------------------
# Learning phases — an ordered 0-to-hero journey toward Full-Stack AI Engineer.
# ---------------------------------------------------------------------------
PHASES: list[dict] = [
    {
        "id": "foundations",
        "title": "Foundations",
        "subtitle": "How computers, the internet, and code actually work",
        "accent": "#6366f1",
    },
    {
        "id": "math",
        "title": "Math for Engineers",
        "subtitle": "From counting to calculus — the math AI is built on",
        "accent": "#8b5cf6",
    },
    {
        "id": "programming",
        "title": "Programming Core",
        "subtitle": "Python, the terminal, Git, and how to think in code",
        "accent": "#0ea5e9",
    },
    {
        "id": "data",
        "title": "Working with Data",
        "subtitle": "Databases, NumPy, Pandas, and telling stories with data",
        "accent": "#06b6d4",
    },
    {
        "id": "web",
        "title": "Web & Full-Stack",
        "subtitle": "Build real apps — frontend, backend, and APIs",
        "accent": "#10b981",
    },
    {
        "id": "ai",
        "title": "AI & Machine Learning",
        "subtitle": "From first model to LLMs, vision, and RAG apps",
        "accent": "#f59e0b",
    },
    {
        "id": "craft",
        "title": "Engineering Craft",
        "subtitle": "Clean code, testing, design, and writing that ships",
        "accent": "#ef4444",
    },
    {
        "id": "devops",
        "title": "DevOps & Cloud",
        "subtitle": "Docker, CI/CD, AWS, Kubernetes, and running things in production",
        "accent": "#ec4899",
    },
    {
        "id": "career",
        "title": "Career",
        "subtitle": "Turn all of this into a job and a community",
        "accent": "#14b8a6",
    },
]


def _t(
    topic_id: str,
    title: str,
    phase: str,
    icon: str,
    blurb: str,
    tool: Optional[str],
    concepts: list[str],
    project: str,
) -> dict:
    return {
        "id": topic_id,
        "title": title,
        "phase": phase,
        "icon": icon,
        "hours": "4-5",
        "blurb": blurb,
        "tool": tool,  # free practice environment, or None for pen-and-paper
        "concepts": concepts,
        "project": project,
    }


# ---------------------------------------------------------------------------
# Topics. Order within a phase = recommended learning order.
# ---------------------------------------------------------------------------
_TOPIC_LIST: list[dict] = [
    # ----------------------------- FOUNDATIONS -----------------------------
    _t(
        "what-is-cs", "What is Computer Science", "foundations", "🧠",
        "The big picture: what computer science actually is, before any code.",
        None,
        [
            "What is CS (science of computation, not just coding)",
            "Brief history (Turing, Von Neumann, transistors, Moore's law)",
            "What is an algorithm (step-by-step problem solving)",
            "What is abstraction (layers: hardware -> OS -> language -> app)",
            "Fields of CS (AI, systems, theory, security, data, web)",
            "Computational thinking (decomposition, pattern recognition, abstraction)",
            "Career paths (developer, data scientist, ML engineer, DevOps, researcher)",
            "Open source and the CS community",
            "How CS differs from software engineering",
            "The CS mindset (problem -> model -> algorithm -> code -> test)",
        ],
        "Write a \"field guide to CS\" document explaining 5 CS fields to a non-technical friend",
    ),
    _t(
        "how-computers-work", "How Computers Work", "foundations", "🖥️",
        "Follow a program from your keyboard all the way down to the transistors.",
        None,
        [
            "Hardware components (CPU, RAM, storage, GPU, motherboard)",
            "How a CPU works (fetch-decode-execute cycle)",
            "Binary (bits, bytes, how computers represent numbers)",
            "How text is stored (ASCII, Unicode, UTF-8)",
            "How images are stored (pixels, RGB values)",
            "How programs run (source code -> compiler/interpreter -> machine code)",
            "Memory (RAM vs storage, volatile vs persistent)",
            "Operating system role (managing hardware, running programs)",
            "File systems (how files are organized on disk)",
            "Input/Output (keyboard, screen, network — how data enters and leaves)",
            "What happens when you press Enter on a command",
            "Abstraction layers (transistor -> gate -> chip -> OS -> app -> user)",
        ],
        "Trace the journey of \"Hello World\" from code to screen — write a visual explainer",
    ),
    _t(
        "how-internet-works", "How the Internet Works", "foundations", "🌐",
        "What really happens between typing a URL and a page appearing.",
        None,
        [
            "What is the internet (network of networks)",
            "IP addresses (what they are, IPv4, IPv6 concept)",
            "DNS (domain names -> IP addresses, like a phone book)",
            "HTTP (request-response cycle, methods: GET/POST)",
            "URLs (anatomy: protocol, domain, path, query params)",
            "What happens when you type a URL in a browser",
            "Client-server model",
            "Ports (what they are, common ports: 80, 443, 3000)",
            "HTTPS and encryption (TLS, why the lock icon matters)",
            "APIs (how apps talk to each other over HTTP)",
            "Cookies and sessions (how websites remember you)",
            "Status codes (200 OK, 404 Not Found, 500 Server Error)",
            "Latency, bandwidth, throughput (speed concepts)",
        ],
        "Use curl/fetch to call 3 public APIs and explain the request-response cycle",
    ),
    _t(
        "operating-systems", "Operating Systems Basics", "foundations", "⚙️",
        "The invisible manager that runs every program on your machine.",
        None,
        [
            "What is an OS (resource manager, abstraction layer)",
            "Processes (what they are, how they run, PID)",
            "Multitasking (how OS runs multiple programs at once)",
            "Memory management (RAM allocation, virtual memory concept)",
            "File systems (directories, paths, permissions)",
            "Users and permissions (root, user accounts, access control)",
            "System calls (how programs talk to the OS)",
            "Kernel vs user space",
            "Common operating systems (Linux, macOS, Windows)",
            "Device drivers (how OS talks to hardware)",
            "Boot process (what happens when you turn on a computer)",
            "Background services/daemons",
        ],
        "Explore your own OS — document processes, memory, and file system using terminal commands",
    ),
    _t(
        "networking", "Networking", "foundations", "🛰️",
        "How data actually travels across the world in milliseconds.",
        None,
        [
            "Network types (LAN, WAN, internet)",
            "TCP/IP model (4 layers: link, internet, transport, application)",
            "IP addresses and subnetting basics",
            "TCP vs UDP (reliable vs fast)",
            "Ports and sockets",
            "How data travels (packets, routing)",
            "HTTP deep (headers, methods, request/response bodies)",
            "DNS deep (recursive resolution, record types: A, CNAME, MX)",
            "Firewalls (what they do, inbound/outbound rules)",
            "VPN (what it is, how it works)",
            "Network tools (ping, traceroute, netstat, curl)",
            "NAT (network address translation, why your home has one IP)",
            "Wireless (Wi-Fi basics, security: WPA)",
        ],
        "Map your network — use ping, traceroute, and netstat to document how data flows",
    ),
    # -------------------------------- MATH --------------------------------
    _t(
        "pre-algebra", "Pre-Algebra & Arithmetic", "math", "➗",
        "Rebuild math from zero — numbers, fractions, and real-world word problems.",
        None,
        [
            "Number types (whole, integer, rational, real)",
            "Addition, subtraction, multiplication, division",
            "Order of operations (PEMDAS/BODMAS)",
            "Fractions (all operations, simplifying)",
            "Decimals (converting, operations)",
            "Percentages (calculating, percent change)",
            "Negative numbers and absolute value",
            "Ratios and proportions",
            "Exponents (whole, zero, negative)",
            "Square roots",
            "Scientific notation",
            "Rounding and estimation",
            "Word problems (translating English to math)",
        ],
        "Real-world budget calculator (pen-and-paper, or Python if known)",
    ),
    _t(
        "algebra", "Algebra", "math", "📐",
        "Variables, equations, and functions — the language of everything quantitative.",
        None,
        [
            "Variables and expressions",
            "Solving linear equations",
            "Inequalities (solving, graphing)",
            "Coordinate plane and plotting points",
            "Slope and linear functions (y = mx + b)",
            "Systems of equations (substitution)",
            "Exponent rules",
            "Polynomials and factoring basics",
            "Quadratic formula (using it)",
            "Functions (definition, f(x), domain, range)",
            "Interval notation",
            "Function composition f(g(x))",
            "Logarithms (definition, basic properties)",
            "Sequences (arithmetic, geometric)",
            "Summation notation basics",
        ],
        "Equation solver and function grapher in Python",
    ),
    _t(
        "statistics", "Statistics & Probability", "math", "🎲",
        "Make sense of data and chance — the foundation of all machine learning.",
        None,
        [
            "What is statistics (descriptive vs inferential)",
            "Mean, median, mode (when to use each)",
            "Variance and standard deviation",
            "Quartiles, IQR, box plots",
            "Z-scores and standardization",
            "Normal distribution (bell curve, 68-95-99.7)",
            "Basic probability (sample space, events)",
            "Conditional probability",
            "Bayes' theorem (intuition)",
            "Permutations vs combinations",
            "Sampling and bias",
            "Confidence intervals (concept)",
            "Hypothesis testing (null/alternative, p-values)",
            "Correlation (Pearson, correlation != causation)",
            "Simple linear regression (line of best fit, R^2)",
        ],
        "Analyze a real dataset — compute stats, visualize, and draw conclusions",
    ),
    _t(
        "linear-algebra", "Linear Algebra", "math", "🧮",
        "Vectors and matrices — how neural networks actually do their math.",
        None,
        [
            "Scalars, vectors, matrices (what they are)",
            "Vector operations (add, subtract, scalar multiply)",
            "Dot product (formula, geometric meaning)",
            "Vector norms (magnitude)",
            "Matrix operations (add, multiply)",
            "Matrix multiplication (rules, dimensions)",
            "Matrix transpose",
            "Identity and inverse matrices",
            "Determinant (2x2, geometric meaning)",
            "Systems of equations as matrices (Ax = b)",
            "Linear independence",
            "Eigenvalues and eigenvectors (intuition)",
            "Linear transformations (rotation, scaling as matrices)",
            "PCA (concept — why eigenvalues matter for data)",
            "All operations verified in NumPy",
        ],
        "Matrix calculator or transformation visualizer",
    ),
    _t(
        "calculus", "Calculus", "math", "📈",
        "Rates of change and optimization — the engine behind gradient descent.",
        None,
        [
            "What is calculus (rates of change, accumulation)",
            "Limits (intuition, notation)",
            "Derivatives (rate of change, slope of tangent)",
            "Basic derivative rules (power, constant, sum)",
            "Product rule and chain rule",
            "Finding maxima and minima (critical points)",
            "Optimization problems",
            "Gradient (partial derivatives, gradient vector)",
            "Gradient descent (intuition — walking downhill)",
            "Learning rate concept",
            "Integrals (area under curve, antiderivative)",
            "Basic integration rules",
            "Definite integrals and Fundamental Theorem",
            "Multivariable calculus preview (partial derivatives)",
        ],
        "Gradient descent visualizer or optimization solver",
    ),
    # ----------------------------- PROGRAMMING -----------------------------
    _t(
        "python", "Python", "programming", "🐍",
        "Your first programming language — from variables all the way to OOP.",
        "Google Colab (colab.research.google.com)",
        [
            "What is code, what is Python, running scripts",
            "Variables and data types (int, float, str, bool)",
            "Operators (arithmetic, comparison, logical)",
            "Strings (f-strings, slicing, methods)",
            "Input/output (print, input)",
            "Conditionals (if, elif, else)",
            "Loops (for, while, range, break, continue)",
            "Lists (create, access, methods, slicing)",
            "List comprehensions",
            "Dictionaries (create, access, methods)",
            "Functions (def, parameters, return)",
            "*args, **kwargs, scope",
            "File I/O (open, read, write, with)",
            "Error handling (try, except, raise)",
            "Modules and imports",
            "OOP: classes, objects, __init__, self",
            "OOP: methods, instance vs class variables",
            "OOP: inheritance, super()",
            "OOP: __str__, __repr__",
            "Virtual environments and pip",
        ],
        "CLI task manager with file storage and OOP design",
    ),
    _t(
        "linux", "Linux & Command Line", "programming", "🐧",
        "Live in the terminal — navigate, automate, and feel like a real engineer.",
        "A terminal (or replit.com for a free browser shell)",
        [
            "What is the terminal/shell",
            "Navigation (pwd, ls, cd)",
            "File operations (touch, mkdir, cp, mv, rm)",
            "Viewing files (cat, less, head, tail)",
            "Searching (grep, find)",
            "Pipes and redirection (|, >, >>)",
            "File permissions (chmod, rwx)",
            "Environment variables ($PATH, export)",
            "Package management (apt, brew)",
            "Process management (ps, kill, Ctrl+C)",
            "SSH basics",
            "Archiving (tar, zip)",
            "Aliases and .bashrc",
            "History and shortcuts (Ctrl+R, tab completion)",
        ],
        "Automated file organizer bash script",
    ),
    _t(
        "git", "Git & GitHub", "programming", "🔀",
        "Version control — never lose work, and share your projects with the world.",
        "A terminal + a free github.com account",
        [
            "What is version control, why it matters",
            "git init, the .git directory",
            "Working directory, staging area, repository",
            "git add, git commit, git status, git log",
            "Writing good commit messages",
            ".gitignore",
            "Branching (git branch, git checkout/switch)",
            "Merging (fast-forward, three-way)",
            "Merge conflicts (identifying, resolving)",
            "git diff (reading diffs)",
            "git stash",
            "git reset vs git revert",
            "Remote repos (push, pull, fetch, clone)",
            "GitHub (creating repos, README, PRs)",
            "Forking and contributing",
        ],
        "Set up a real project with branches, commits, and a polished GitHub repo",
    ),
    _t(
        "dsa", "Data Structures & Algorithms", "programming", "🧩",
        "How to store data and solve problems efficiently — the core of good code.",
        "Google Colab (colab.research.google.com)",
        [
            "What is a data structure, what is an algorithm",
            "Big-O notation (O(1), O(n), O(n^2), O(log n))",
            "Arrays/Lists (access, insert, delete complexities)",
            "Hash maps (how dicts work, O(1) lookup)",
            "Stacks (LIFO, push/pop)",
            "Queues (FIFO, enqueue/dequeue)",
            "The Node class (what it is, why it matters)",
            "Linked lists (singly, traversal, insert, delete)",
            "Trees (terminology, binary trees, traversals)",
            "Binary Search Trees (search, insert)",
            "Graphs (terminology, adjacency list)",
            "BFS and DFS",
            "Binary search",
            "Sorting (merge sort, quick sort concepts)",
            "Basic recursion (base case, recursive case)",
            "Basic DP concept (memoization, fibonacci)",
        ],
        "Build a linked list and BST from scratch with all operations",
    ),
    # -------------------------------- DATA --------------------------------
    _t(
        "sql", "SQL", "data", "🗄️",
        "Talk to databases — pull answers out of millions of rows with a query.",
        "sqliteonline.com (free, browser-based)",
        [
            "What is a database, what is SQL",
            "Tables, rows, columns, primary keys",
            "SELECT, WHERE, ORDER BY, LIMIT",
            "Aggregate functions (COUNT, SUM, AVG, MIN, MAX)",
            "GROUP BY and HAVING",
            "JOINs (INNER, LEFT, RIGHT)",
            "Subqueries",
            "CTEs (WITH clause)",
            "Window functions (ROW_NUMBER, RANK, LAG, LEAD)",
            "INSERT, UPDATE, DELETE",
            "CASE WHEN",
            "String and date functions",
            "Indexes (what, why)",
            "Transactions and ACID (concept)",
            "Views",
        ],
        "Business analytics queries on a real dataset (revenue, segments, trends)",
    ),
    _t(
        "database-design", "Database Design", "data", "🏛️",
        "Design data models that scale — relational, NoSQL, and how to choose.",
        "sqliteonline.com / a free MongoDB Atlas account",
        [
            "Relational database concepts",
            "Entities, attributes, relationships",
            "ER diagrams",
            "Normalization (1NF, 2NF, 3NF)",
            "Primary and foreign keys",
            "Constraints (NOT NULL, UNIQUE, CHECK)",
            "Junction tables (M:N relationships)",
            "Indexes (B-tree concept)",
            "PostgreSQL basics (setup, psql, data types)",
            "Python + PostgreSQL (psycopg2 basics)",
            "ORM concept (SQLAlchemy basics)",
            "NoSQL concept (MongoDB documents)",
            "MongoDB CRUD basics",
            "SQL vs NoSQL decision framework",
        ],
        "Design and implement a database schema for a real application",
    ),
    _t(
        "numpy", "NumPy", "data", "🔢",
        "Fast number-crunching in Python — the foundation of all data & AI libraries.",
        "Google Colab (colab.research.google.com)",
        [
            "What is NumPy, why arrays not lists",
            "Creating arrays (array, zeros, ones, arange, linspace)",
            "Array attributes (shape, dtype, ndim)",
            "Indexing and slicing",
            "Boolean indexing",
            "Reshaping (reshape, flatten)",
            "Element-wise operations",
            "Broadcasting rules",
            "Aggregation (sum, mean, std, min, max)",
            "Aggregation along axes",
            "np.where and comparison operations",
            "Stacking and splitting",
            "Linear algebra (dot, matmul, linalg)",
            "Random generation",
            "Vectorization (replacing loops)",
        ],
        "Image processor (load image as array, apply filters)",
    ),
    _t(
        "pandas", "Pandas", "data", "🐼",
        "The spreadsheet superpower — clean, transform, and analyze real datasets.",
        "Google Colab (colab.research.google.com)",
        [
            "What is Pandas (Series, DataFrame)",
            "Loading data (read_csv, read_excel)",
            "Viewing data (head, info, describe, shape)",
            "Selecting (loc, iloc)",
            "Filtering with conditions",
            "Sorting (sort_values)",
            "Missing data (isna, dropna, fillna)",
            "Data types and conversion",
            "String methods (.str accessor)",
            "GroupBy and aggregation",
            "Merging and joining",
            "Reshaping (pivot, melt)",
            "Apply and lambda",
            "DateTime handling",
            "Value counts and crosstab",
        ],
        "End-to-end data cleaning and analysis on a real Kaggle dataset",
    ),
    _t(
        "matplotlib", "Matplotlib & Seaborn", "data", "📊",
        "Turn numbers into pictures — charts that make data tell a story.",
        "Google Colab (colab.research.google.com)",
        [
            "Figure and Axes objects",
            "Line plots",
            "Bar charts",
            "Histograms",
            "Scatter plots",
            "Box plots",
            "Subplots",
            "Customization (titles, labels, legends, colors)",
            "Saving figures",
            "Seaborn: distribution plots (histplot, kdeplot)",
            "Seaborn: categorical plots (barplot, boxplot, violinplot)",
            "Seaborn: heatmaps",
            "Seaborn: pair plots",
            "Choosing the right chart for the data",
        ],
        "Multi-chart dashboard telling a data story from a real dataset",
    ),
    _t(
        "data-analysis", "Data Analysis", "data", "🔍",
        "Think like an analyst — from raw data to a decision someone can act on.",
        "Google Colab (colab.research.google.com)",
        [
            "What is data analysis (descriptive, diagnostic, predictive, prescriptive)",
            "The analyst workflow",
            "Data quality dimensions",
            "EDA methodology",
            "Data cleaning strategies",
            "Business metrics (KPIs, conversion, retention)",
            "Funnel analysis",
            "Cohort analysis",
            "A/B testing basics",
            "Correlation analysis",
            "Data storytelling",
            "Choosing the right visualization",
            "Common analytical mistakes (survivorship bias, Simpson's paradox)",
            "Ethics of data",
        ],
        "Full EDA on a real dataset with narrative and visualizations",
    ),
    # --------------------------------- WEB ---------------------------------
    _t(
        "html-css", "HTML & CSS", "web", "🎨",
        "Build and style your first web pages — structure and design from scratch.",
        "codepen.io (free, browser-based)",
        [
            "What is HTML (document structure)",
            "Text elements (headings, paragraphs, links, images)",
            "Lists and tables",
            "Forms (input types, labels, buttons)",
            "Semantic HTML (header, nav, main, footer)",
            "What is CSS (selectors, properties)",
            "Box model (margin, padding, border)",
            "Display (block, inline, inline-block)",
            "Flexbox (justify-content, align-items, gap)",
            "CSS Grid basics",
            "Responsive design (media queries)",
            "Colors, typography, Google Fonts",
            "Transitions and basic animations",
            "CSS variables",
        ],
        "Responsive personal portfolio page",
    ),
    _t(
        "javascript", "JavaScript", "web", "✨",
        "The language of the web — make pages interactive and talk to APIs.",
        "codepen.io (free, browser-based)",
        [
            "What is JavaScript, where it runs",
            "Variables (let, const), data types",
            "Operators (arithmetic, comparison, === vs ==)",
            "Strings (template literals, methods)",
            "Conditionals (if/else, ternary)",
            "Loops (for, while, for...of)",
            "Arrays (create, methods: push, pop, map, filter, reduce)",
            "Objects (create, access, destructuring)",
            "Functions (declaration, arrow, callbacks)",
            "Scope and closures (basics)",
            "DOM manipulation (querySelector, textContent, classList)",
            "Events (addEventListener, click, submit)",
            "Promises and async/await",
            "Fetch API (GET requests)",
            "JSON (parse, stringify)",
        ],
        "Interactive web app using DOM manipulation and a public API",
    ),
    _t(
        "typescript", "TypeScript", "web", "🔷",
        "JavaScript with a safety net — catch bugs before they happen.",
        "typescriptlang.org/play (free, browser-based)",
        [
            "What is TypeScript, why types",
            "Basic types (string, number, boolean, any)",
            "Type annotations (variables, functions)",
            "Type inference",
            "Arrays and tuples",
            "Objects and interfaces",
            "Type aliases",
            "Union types and narrowing",
            "Enums",
            "Generics (basics)",
            "Utility types (Partial, Pick, Omit)",
            "Type assertions",
            "Classes with TypeScript",
            "Working with third-party types",
        ],
        "Convert a previous JS project to fully typed TypeScript",
    ),
    _t(
        "react", "React", "web", "⚛️",
        "Build modern UIs from reusable components — the most popular frontend tool.",
        "stackblitz.com (free, browser-based)",
        [
            "What is React, why components",
            "JSX basics",
            "Components (function components)",
            "Props (passing data, destructuring)",
            "useState (state management)",
            "Event handling (onClick, onChange)",
            "Conditional rendering",
            "Rendering lists (map, keys)",
            "useEffect (side effects, dependency array)",
            "useRef (DOM references)",
            "Custom hooks (basics)",
            "Lifting state up",
            "Context API (basics)",
            "React Router (basic routing)",
            "Fetching data (useEffect + fetch)",
            "Tailwind CSS with React",
        ],
        "Multi-page app with routing, state, API data, and Tailwind styling",
    ),
    _t(
        "nextjs", "Next.js", "web", "▲",
        "The production React framework — routing, server rendering, and deploy.",
        "A terminal + a free Vercel account",
        [
            "What is Next.js, why over plain React",
            "App Router (file-based routing)",
            "Dynamic routes",
            "Layouts (root, nested)",
            "Server Components vs Client Components",
            "Data fetching in Server Components",
            "Loading and error pages",
            "API Routes (route handlers)",
            "Server Actions (form handling)",
            "Image and font optimization",
            "Metadata and SEO",
            "Environment variables",
            "Deployment (Vercel)",
        ],
        "Full Next.js app with dynamic routes, API routes, and deployment",
    ),
    _t(
        "fastapi", "FastAPI", "web", "🚀",
        "Build fast, modern backend APIs in Python — with auto docs and auth.",
        "A terminal (local Python) or replit.com",
        [
            "What is an API, what is REST",
            "What is FastAPI, setting up",
            "First endpoint (GET)",
            "Path and query parameters",
            "Request body (Pydantic models)",
            "HTTP methods (GET, POST, PUT, DELETE)",
            "Status codes and HTTPException",
            "Response models",
            "Dependency injection (Depends)",
            "Router organization (APIRouter)",
            "CORS middleware",
            "Database integration basics (SQLAlchemy)",
            "JWT authentication basics",
            "Testing (TestClient)",
            "Auto-generated docs (/docs)",
        ],
        "Full CRUD API with auth, database, and auto-docs",
    ),
    _t(
        "auth-security", "Auth & Security", "web", "🔐",
        "Log users in safely and keep the bad guys out — the essentials every app needs.",
        "A terminal (local Python/Node)",
        [
            "Authentication vs authorization",
            "Password hashing (bcrypt)",
            "Session-based vs token-based auth",
            "JWT (structure, create, verify)",
            "OAuth 2.0 (concept, flow)",
            "API keys",
            "RBAC (roles, permissions)",
            "HTTPS and TLS",
            "CORS (what, why, how to fix)",
            "XSS, CSRF, SQL injection (what they are, prevention)",
            "Rate limiting",
            "Input validation",
            "OWASP Top 10 (overview)",
        ],
        "Complete auth system (signup, login, JWT, protected routes)",
    ),
    _t(
        "api-design", "API Design", "web", "🧬",
        "Design APIs other developers love to use — clean, consistent, and documented.",
        "A terminal + swagger.io editor",
        [
            "What is an API (application programming interface)",
            "REST principles (resources, statelessness, uniform interface)",
            "URL/endpoint design (nouns not verbs, nesting)",
            "HTTP methods mapped to CRUD (GET=read, POST=create, PUT=update, DELETE=delete)",
            "Status codes (when to use 200, 201, 204, 400, 401, 403, 404, 500)",
            "Request and response formats (JSON)",
            "Query parameters vs path parameters",
            "Pagination (offset, cursor-based)",
            "Filtering, sorting, searching in APIs",
            "API versioning (URL, header)",
            "Error response format (consistent error objects)",
            "Rate limiting (what, why)",
            "API documentation (OpenAPI/Swagger)",
            "GraphQL vs REST (concept, tradeoffs)",
        ],
        "Design a complete API specification (endpoints, methods, params, responses) for a real app",
    ),
    # --------------------------------- AI ---------------------------------
    _t(
        "machine-learning", "Machine Learning", "ai", "🤖",
        "Teach computers to learn from data — your first real ML models.",
        "Google Colab (colab.research.google.com)",
        [
            "What is ML (supervised, unsupervised)",
            "ML workflow (data -> preprocess -> train -> evaluate)",
            "Train/test/validation split (why 3 sets)",
            "Feature scaling (standardization, normalization)",
            "Linear regression (concept, fitting, R^2)",
            "Logistic regression (classification, sigmoid)",
            "Decision trees (splitting, intuition)",
            "Random forests (ensemble, bagging)",
            "K-means clustering (algorithm, elbow method)",
            "PCA (dimensionality reduction concept)",
            "Overfitting vs underfitting",
            "Cross-validation (k-fold)",
            "Metrics (accuracy, precision, recall, F1, confusion matrix)",
            "Scikit-learn API (fit, predict, transform)",
            "Pipeline objects (preprocessing + model)",
        ],
        "End-to-end ML pipeline (load data, preprocess, train, evaluate, compare models)",
    ),
    _t(
        "deep-learning", "Deep Learning", "ai", "🧠",
        "Neural networks demystified — build an image classifier with PyTorch.",
        "Google Colab (colab.research.google.com, free GPU)",
        [
            "What is deep learning, how it differs from ML",
            "Neural network structure (input, hidden, output)",
            "How neurons work (weights, bias, activation)",
            "Activation functions (ReLU, sigmoid, softmax)",
            "Forward pass (concept)",
            "Loss functions (MSE, cross-entropy)",
            "Backpropagation (concept — learning from mistakes)",
            "Gradient descent and learning rate",
            "Epochs, batches, iterations",
            "Overfitting prevention (dropout, early stopping)",
            "CNNs (convolution, pooling — how computers see)",
            "RNNs/LSTMs (sequence data — concept)",
            "Transformers and attention (concept)",
            "Transfer learning (using pretrained models)",
            "PyTorch basics (tensors, nn.Module, training loop)",
        ],
        "Image classifier using transfer learning (pretrained ResNet on custom images)",
    ),
    _t(
        "nlp", "NLP", "ai", "💬",
        "Teach machines to understand language — from word counts to transformers.",
        "Google Colab (colab.research.google.com, free GPU)",
        [
            "What is NLP, applications",
            "Text preprocessing (tokenization, stopwords, stemming)",
            "Bag of Words and TF-IDF",
            "Word embeddings (Word2Vec concept, similarity)",
            "Attention mechanism (intuition)",
            "Transformer architecture (concept)",
            "BERT (concept — bidirectional understanding)",
            "GPT (concept — text generation)",
            "Hugging Face (pipeline, loading models)",
            "Text classification with transformers",
            "NER (concept, using pretrained)",
            "Text generation (using GPT-2)",
            "Tokenizers (BPE, WordPiece)",
            "Evaluation metrics (BLEU, ROUGE)",
            "LLMs overview and limitations",
        ],
        "Sentiment analysis system using Hugging Face on real reviews",
    ),
    _t(
        "computer-vision", "Computer Vision", "ai", "👁️",
        "Give computers eyes — process images and recognize what's in them.",
        "Google Colab (colab.research.google.com, free GPU)",
        [
            "What is CV, applications",
            "Images as data (pixels, channels, tensors)",
            "Image loading (PIL, OpenCV)",
            "Image operations (resize, crop, rotate, color convert)",
            "Image filtering (blur, sharpen, edge detection)",
            "Thresholding and contour detection",
            "CNNs for image classification",
            "Transfer learning for vision",
            "Data augmentation",
            "Object detection (concept, YOLO)",
            "Segmentation (concept)",
            "GANs and diffusion models (concept)",
            "Vision Transformers (concept)",
            "OpenCV vs torchvision vs PIL",
        ],
        "Image classifier on custom dataset or object counter using a pretrained model",
    ),
    _t(
        "reinforcement-learning", "Reinforcement Learning", "ai", "🕹️",
        "Train agents that learn by trial and error — the AI behind game-playing bots.",
        "Google Colab (colab.research.google.com)",
        [
            "What is RL (agent, environment, reward)",
            "How RL differs from supervised/unsupervised",
            "MDP (states, actions, transitions, rewards)",
            "Policy (mapping states to actions)",
            "Value functions (V(s), Q(s,a))",
            "Bellman equations (concept)",
            "Exploration vs exploitation (epsilon-greedy)",
            "Q-learning algorithm",
            "DQN (concept — neural nets for Q-values)",
            "Policy gradients (concept)",
            "OpenAI Gymnasium (environments, step, reset)",
            "Reward shaping",
            "Applications (games, robotics)",
        ],
        "Train a Q-learning agent to solve CartPole or FrozenLake",
    ),
    _t(
        "rag", "RAG, Embeddings & AI Apps", "ai", "🧲",
        "Build ChatGPT-style apps over your own documents — the hottest AI skill today.",
        "Google Colab + a free LLM API key",
        [
            "What are embeddings (representing anything as a vector)",
            "How embeddings work (semantic similarity, vector space)",
            "Text embeddings (sentence-transformers, OpenAI embeddings)",
            "Vector similarity (cosine similarity, dot product)",
            "Vector databases (ChromaDB, Pinecone, pgvector concept)",
            "What is RAG (Retrieval-Augmented Generation)",
            "RAG architecture (embed documents -> store -> query -> retrieve -> generate)",
            "Chunking strategies (how to split documents for embedding)",
            "Building a RAG pipeline from scratch",
            "LLM APIs (OpenAI, Anthropic — calling, handling responses)",
            "Prompt engineering for RAG (system prompts, context injection)",
            "Evaluation (relevance, faithfulness, answer quality)",
            "Multimodal embeddings (text + image)",
            "Applications (document Q&A, semantic search, chatbots, knowledge bases)",
        ],
        "Build a RAG system — upload documents, embed, store in ChromaDB, query with natural language",
    ),
    # -------------------------------- CRAFT --------------------------------
    _t(
        "software-engineering", "Software Engineering Practices", "craft", "🛠️",
        "How professional teams actually build software — process, reviews, clean code.",
        "A terminal + a GitHub repo",
        [
            "What is software engineering (vs coding)",
            "SDLC (Software Development Life Cycle)",
            "Agile methodology (manifesto, principles)",
            "Scrum (sprints, daily standups, retrospectives, roles)",
            "Kanban (board, WIP limits, flow)",
            "User stories and requirements",
            "Code reviews (what to look for, giving feedback)",
            "Technical debt (what it is, managing it)",
            "Estimation (story points, t-shirt sizing)",
            "Clean code principles (naming, functions, DRY, KISS)",
            "Refactoring (when, how, common patterns)",
            "Documentation (README, ADRs, inline comments — when each)",
            "Pair programming and mob programming",
            "Retrospectives (what went well, what didn't, actions)",
        ],
        "Take a previous messy project, refactor it with clean code principles, add docs and a proper README",
    ),
    _t(
        "oo-design", "Object-Oriented Design", "craft", "🧱",
        "Design code that's easy to change — SOLID principles and design patterns.",
        "Google Colab (colab.research.google.com)",
        [
            "OOP review (classes, objects, inheritance, polymorphism)",
            "SOLID principles: Single Responsibility",
            "SOLID: Open/Closed Principle",
            "SOLID: Liskov Substitution",
            "SOLID: Interface Segregation",
            "SOLID: Dependency Inversion",
            "Composition over inheritance (when and why)",
            "Design patterns: Factory (creating objects)",
            "Design patterns: Observer (event handling)",
            "Design patterns: Strategy (swappable algorithms)",
            "Design patterns: Singleton (one instance)",
            "Anti-patterns (god object, spaghetti code)",
            "UML class diagrams (reading and drawing)",
            "Designing class hierarchies from requirements",
        ],
        "Design and implement a class system for a real scenario (library, e-commerce, game) using SOLID and patterns",
    ),
    _t(
        "testing", "Testing & Code Quality", "craft", "✅",
        "Write code that stays correct — tests, debugging, linting, and type checks.",
        "A terminal (local Python)",
        [
            "Why testing matters",
            "Testing pyramid (unit, integration, E2E)",
            "pytest basics (test functions, assertions)",
            "Fixtures",
            "Parameterized tests",
            "Mocking basics",
            "TDD (red-green-refactor)",
            "Testing FastAPI endpoints",
            "Test coverage",
            "Debugging (tracebacks, pdb)",
            "Linting (ruff, flake8)",
            "Formatting (black)",
            "Type checking (mypy basics)",
            "Documentation (docstrings, README)",
        ],
        "Add comprehensive tests to a previous project (>80% coverage)",
    ),
    _t(
        "technical-writing", "Technical Writing", "craft", "✍️",
        "Communicate your work clearly — READMEs, docs, and blog posts that land.",
        "A Markdown editor (or GitHub)",
        [
            "Why technical writing matters",
            "README structure (name, description, install, usage, examples)",
            "Writing clear documentation",
            "API documentation (describing endpoints, params, responses)",
            "Code comments (when to comment, when not to)",
            "Writing technical blog posts (structure, audience)",
            "Writing reports (executive summary, methods, results)",
            "Academic paper structure (abstract, intro, method, results, conclusion)",
            "Citing sources and references",
            "Markdown mastery (headers, lists, code blocks, links, tables, images)",
            "Diagrams (Mermaid, ASCII diagrams, architecture diagrams)",
            "Writing clearly (active voice, short sentences, one idea per paragraph)",
        ],
        "Write a polished technical blog post about something you learned + a professional README for a project",
    ),
    _t(
        "web-scraping", "Web Scraping", "craft", "🕸️",
        "Collect data from the web responsibly — the analyst's data-gathering superpower.",
        "Google Colab (colab.research.google.com)",
        [
            "What is web scraping, when to use it (vs APIs)",
            "How web pages work (HTML structure)",
            "Python requests library (GET, headers, response)",
            "BeautifulSoup (parsing HTML, finding elements)",
            "Selectors (tag, class, id, CSS selectors)",
            "Extracting text, links, images",
            "Handling pagination (following next page links)",
            "Handling dynamic content (concept — JS-rendered pages)",
            "Selenium/Playwright basics (for dynamic pages)",
            "Storing scraped data (CSV, JSON, database)",
            "Rate limiting and politeness (sleep, respecting robots.txt)",
            "Legal and ethical considerations",
            "APIs vs scraping (when to use which)",
        ],
        "Build a web scraper that collects real data, cleans it, and saves to CSV",
    ),
    _t(
        "system-design", "System Design", "craft", "🏗️",
        "Design systems that handle millions of users — the senior-engineer skill.",
        "excalidraw.com (free diagramming)",
        [
            "What is system design, why it matters",
            "Client-server model",
            "DNS and HTTP",
            "Load balancers",
            "Horizontal vs vertical scaling",
            "Caching (what, where, invalidation)",
            "CDNs",
            "Database scaling (replication, sharding)",
            "CAP theorem",
            "Message queues",
            "Microservices vs monolith",
            "API design (REST)",
            "Design process (requirements -> estimation -> architecture)",
            "Common patterns (URL shortener, chat system)",
        ],
        "Design document for a system (architecture diagram, tradeoffs, scaling plan)",
    ),
    # ------------------------------- DEVOPS -------------------------------
    _t(
        "docker", "Docker", "devops", "🐳",
        "Package any app so it runs anywhere — the foundation of modern deployment.",
        "A terminal with Docker Desktop (or play-with-docker.com)",
        [
            "What is Docker (containers vs VMs)",
            "Images vs containers",
            "docker run, ps, stop, rm",
            "Port mapping (-p)",
            "Volume mounting (-v)",
            "Dockerfile (FROM, COPY, RUN, CMD)",
            "Building images (docker build)",
            ".dockerignore",
            "Multi-stage builds",
            "Docker Compose (services, ports, volumes)",
            "Docker Compose commands (up, down, build)",
            "Containerizing a Python app",
            "Containerizing a Next.js app",
            "Docker for databases",
            "Best practices (small images, non-root)",
        ],
        "Containerize a full-stack app (frontend + backend + database in Compose)",
    ),
    _t(
        "cicd", "CI/CD", "devops", "🔁",
        "Automate testing and deployment — ship code safely with GitHub Actions.",
        "A GitHub repo (Actions are free)",
        [
            "What is CI, what is CD",
            "Why automate (faster feedback, fewer bugs)",
            "GitHub Actions (workflow files, YAML)",
            "Triggers (push, pull_request)",
            "Jobs and steps",
            "Actions marketplace (checkout, setup-python)",
            "Environment variables and secrets",
            "CI pipeline (lint -> test -> build)",
            "CD pipeline (CI + deploy)",
            "Branch protection",
            "Caching dependencies",
            "Docker in CI",
            "Deployment strategies (blue-green, canary concept)",
        ],
        "Full CI/CD pipeline for a real project (lint + test + deploy)",
    ),
    _t(
        "cloud-aws", "Cloud / AWS", "devops", "☁️",
        "Run your apps on the world's biggest cloud — the essential AWS services.",
        "A free-tier AWS account",
        [
            "What is cloud computing (IaaS, PaaS, SaaS)",
            "AWS overview (regions, AZs)",
            "IAM (users, roles, policies)",
            "EC2 (launching, SSH, security groups)",
            "S3 (buckets, objects, static hosting)",
            "RDS (managed databases)",
            "Lambda (serverless functions)",
            "API Gateway",
            "CloudWatch (monitoring, logs)",
            "VPC basics",
            "Cost management (free tier, billing alerts)",
            "AWS CLI and Boto3",
            "Deploying a FastAPI app to AWS",
        ],
        "Deploy a real application to AWS (EC2 or Lambda + S3)",
    ),
    _t(
        "kubernetes", "Kubernetes", "devops", "☸️",
        "Orchestrate containers at scale — the platform running the modern internet.",
        "minikube on your machine (or killercoda.com playground)",
        [
            "Why Kubernetes (Docker alone isn't enough at scale)",
            "Container orchestration (what it means)",
            "Kubernetes architecture (master node, worker nodes)",
            "Pods (smallest unit, one or more containers)",
            "Deployments (managing replicas, rolling updates)",
            "Services (exposing pods, ClusterIP, NodePort, LoadBalancer)",
            "ConfigMaps and Secrets (configuration management)",
            "Namespaces (organizing resources)",
            "kubectl basics (get, describe, apply, logs, exec)",
            "YAML manifests (pod, deployment, service definitions)",
            "Scaling (horizontal pod autoscaler)",
            "Health checks (liveness, readiness probes)",
            "Kubernetes vs Docker Compose (when to use which)",
        ],
        "Deploy a multi-container app to a local Kubernetes cluster (minikube)",
    ),
    _t(
        "iac", "Infrastructure as Code", "devops", "📜",
        "Define your whole cloud in code — reproducible infrastructure with Terraform.",
        "A terminal + a free-tier AWS account",
        [
            "What is IaC (managing infrastructure through code, not clicking)",
            "Why IaC (reproducibility, version control, automation)",
            "Terraform basics (providers, resources, state)",
            "HCL syntax (blocks, arguments, variables)",
            "terraform init, plan, apply, destroy",
            "Resources (EC2, S3, RDS definitions in Terraform)",
            "Variables and outputs",
            "State management (what state is, remote state concept)",
            "Modules (reusable infrastructure components)",
            "Terraform vs CloudFormation vs Pulumi (comparison)",
            "GitOps concept (infrastructure changes through PRs)",
            "Immutable infrastructure (replace, don't modify)",
        ],
        "Define and deploy a complete AWS environment (VPC + EC2 + S3) using Terraform",
    ),
    _t(
        "mlops", "MLOps", "devops", "🔬",
        "Take ML models from notebook to production — track, serve, and monitor them.",
        "Google Colab + a terminal",
        [
            "What is MLOps (ML research -> production gap)",
            "ML lifecycle (data -> train -> deploy -> monitor)",
            "Experiment tracking (MLflow)",
            "Data versioning (DVC concept)",
            "Model versioning and registry",
            "Model serving (FastAPI + model)",
            "Containerized serving (Docker + FastAPI)",
            "A/B testing models",
            "Data drift and model monitoring",
            "CI/CD for ML",
            "Reproducibility (seeds, environment locking)",
            "ML system design patterns",
            "Cost of ML in production",
        ],
        "End-to-end ML pipeline (train -> register -> serve -> monitor)",
    ),
    _t(
        "data-engineering", "Data Engineering", "devops", "🏭",
        "Build the pipelines that feed data to everything — ETL, warehouses, and Spark.",
        "Google Colab + a terminal",
        [
            "What is data engineering (building data pipelines)",
            "Data engineering vs data science vs data analysis",
            "ETL (Extract, Transform, Load) — concept and pipeline",
            "ELT (Extract, Load, Transform) — modern approach",
            "Data sources (databases, APIs, files, streams)",
            "Data formats (CSV, JSON, Parquet, Avro)",
            "Data warehouses (what, why, how — Snowflake, BigQuery concept)",
            "Data lakes (what, why, how — raw storage)",
            "Data lakehouse (combining warehouse + lake)",
            "Apache Spark (concept — distributed data processing)",
            "PySpark basics (SparkSession, DataFrames, transformations)",
            "Data quality (validation, testing, monitoring)",
            "Orchestration (Airflow concept — scheduling pipelines)",
            "Batch vs streaming (when to use each)",
        ],
        "Build a simple ETL pipeline (extract from API -> transform with Python -> load to database)",
    ),
    _t(
        "message-queues", "Message Queues", "devops", "📨",
        "Connect services that don't wait on each other — async systems that scale.",
        "A terminal with Docker",
        [
            "What is a message queue (async communication between services)",
            "Why queues (decoupling, reliability, scaling)",
            "Producer-consumer pattern",
            "Kafka overview (topics, partitions, consumer groups, offsets)",
            "RabbitMQ overview (exchanges, queues, bindings)",
            "When to use Kafka vs RabbitMQ",
            "Event-driven architecture (concept)",
            "Pub/sub pattern",
            "Dead letter queues (handling failed messages)",
            "Message ordering and idempotency",
            "Async processing patterns (task queues, background jobs)",
            "Celery (Python task queue) basics",
        ],
        "Build a producer-consumer system (API receives request -> sends to queue -> worker processes)",
    ),
    _t(
        "monitoring", "Monitoring & Observability", "devops", "📡",
        "Know what your systems are doing — metrics, logs, traces, and alerts.",
        "A terminal with Docker",
        [
            "What is monitoring (knowing what's happening in production)",
            "What is observability (understanding WHY things happen)",
            "Three pillars: metrics, logs, traces",
            "Metrics (what to measure: latency, error rate, throughput, saturation)",
            "Prometheus (concept — time-series metrics collection)",
            "Grafana (concept — dashboards and visualization)",
            "Logging (structured logging, log levels, centralized logging)",
            "Tracing (distributed tracing, following a request across services)",
            "Alerting (when to alert, alert fatigue, runbooks)",
            "SLIs, SLOs, SLAs (defining and measuring reliability)",
            "Health checks and uptime monitoring",
            "Error tracking (Sentry concept)",
            "On-call and incident management basics",
        ],
        "Add monitoring to a previous project (health endpoint, structured logging, basic metrics)",
    ),
    _t(
        "microservices", "Microservices", "devops", "🧩",
        "Split big apps into small services — and know when NOT to.",
        "A terminal with Docker",
        [
            "Monolith vs microservices (what each is)",
            "When to use microservices (and when NOT to — most teams shouldn't)",
            "Service boundaries (how to split a monolith)",
            "Communication (sync: REST/gRPC, async: queues/events)",
            "API gateway (single entry point, routing, auth)",
            "Service discovery (how services find each other)",
            "Data management (database per service, eventual consistency)",
            "Saga pattern (distributed transactions)",
            "Circuit breaker pattern (handling service failures)",
            "Docker + Kubernetes for microservices",
            "Testing microservices (contract testing, integration testing)",
            "Tradeoffs (complexity, debugging, deployment, team structure)",
        ],
        "Split a monolith into 2-3 microservices with independent databases and API gateway",
    ),
    # -------------------------------- CAREER --------------------------------
    _t(
        "tech-career", "Tech Career Development", "career", "🎯",
        "Turn your skills into a job — resume, portfolio, interviews, and negotiation.",
        "Your resume + LinkedIn + GitHub",
        [
            "Types of tech roles (frontend, backend, full-stack, data, ML, DevOps, cloud)",
            "Resume/CV for tech (ATS-friendly, quantifying impact)",
            "Portfolio building (what to include, how to present)",
            "GitHub profile optimization (pinned repos, contributions, README profile)",
            "LinkedIn for tech (headline, about, experience, skills)",
            "Job search strategies (direct apply, referrals, recruiters)",
            "Interview types (phone screen, coding, system design, behavioral)",
            "Behavioral interview (STAR method)",
            "Salary negotiation basics",
            "Evaluating job offers (not just salary — equity, growth, team, culture)",
            "Building a network (conferences, meetups, Twitter, communities)",
            "Personal brand (blog, talks, open source)",
            "Career ladder (junior -> mid -> senior -> staff -> principal)",
        ],
        "Complete job-ready package — updated resume, LinkedIn, GitHub profile, and portfolio plan",
    ),
    _t(
        "open-source", "Open Source Contribution", "career", "💞",
        "Give back and level up — make your first real contribution to a real project.",
        "A GitHub account + a terminal",
        [
            "What is open source (licenses, community, collaboration)",
            "Why contribute (learning, portfolio, network, giving back)",
            "Finding projects to contribute to (good first issues, topic tags)",
            "Reading large codebases (how to navigate, understand architecture)",
            "Forking, cloning, branching workflow",
            "Writing good pull requests (description, context, screenshots)",
            "Code review etiquette (as author and reviewer)",
            "Issue reporting (reproducible bug reports)",
            "Documentation contributions (often the best starting point)",
            "Community norms (CoC, maintainer expectations)",
            "Open source licenses (MIT, Apache, GPL — what they mean)",
            "Building your own open source project",
        ],
        "Make a real contribution to a real open source project (find issue, fix it, submit PR)",
    ),
]

# Indexed lookups.
TOPICS: dict[str, dict] = {topic["id"]: topic for topic in _TOPIC_LIST}


def phases_with_topics() -> list[dict]:
    """Return phases, each with its ordered list of topics (metadata only, no concepts)."""
    result = []
    for phase in PHASES:
        topic_summaries = [
            {
                "id": t["id"],
                "title": t["title"],
                "icon": t["icon"],
                "blurb": t["blurb"],
                "hours": t["hours"],
                "concept_count": len(t["concepts"]),
            }
            for t in _TOPIC_LIST
            if t["phase"] == phase["id"]
        ]
        result.append({**phase, "topics": topic_summaries})
    return result


def get_topic(topic_id: str) -> Optional[dict]:
    return TOPICS.get(topic_id)


TOTAL_TOPICS = len(_TOPIC_LIST)

# Per-topic practice targets (shown as counters on the progress rail).
PROBLEMS_TARGET = 50
PROJECTS_TARGET = 5
